version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql-loja
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - lojamysql_data:/var/lib/mysql-loja
volumes:
  lojamysql_data: